// Export the current Stripe products + prices for an event into a versioned
// TS module under scripts/stripe-definitions/. The output module can then be
// hand-edited and applied to test/live Stripe via `npm run stripe:apply`.
//
// Reads STRIPE_SECRET_KEY from env, falling back to worker/.dev.vars. Use
// whichever Stripe mode (test or live) the key belongs to as the source.
//
// Usage:
//   npm run stripe:export -- --slug=bbu-26-2
//   npm run stripe:export -- --slug=bbu-26-2 --out=scripts/stripe-definitions/bbu-26-2.ts

import Stripe from 'stripe';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { inspect } from 'node:util';
import type { EventDefinition, PriceDefinition, ProductDefinition } from './stripe-definitions/_types';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const workerDir = join(scriptDir, '..');

function arg(name: string): string | undefined {
  const prefix = `--${name}=`;
  return process.argv.find((a) => a.startsWith(prefix))?.slice(prefix.length);
}

const slug = arg('slug');
if (!slug) {
  console.error('Usage: tsx scripts/export-stripe.ts --slug=<event-slug> [--out=<path>]');
  process.exit(1);
}

function readDevVars(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const devVars = readDevVars(join(workerDir, '.dev.vars'));
const stripeKey = process.env.STRIPE_SECRET_KEY ?? devVars.STRIPE_SECRET_KEY;
if (!stripeKey) {
  console.error('STRIPE_SECRET_KEY not found in env or worker/.dev.vars');
  process.exit(1);
}

const stripe = new Stripe(stripeKey, { apiVersion: '2025-02-24.acacia' });

async function listAll<T>(iter: AsyncIterable<T>): Promise<T[]> {
  const out: T[] = [];
  for await (const item of iter) out.push(item);
  return out;
}

const mode = stripeKey.startsWith('sk_live_') ? 'live' : stripeKey.startsWith('sk_test_') ? 'test' : 'unknown';
console.log(`Reading products linked to event "${slug}" from Stripe (${mode} mode)…`);

const allProducts = await listAll(stripe.products.list({ limit: 100 }));
const matching = allProducts.filter((p) => p.metadata?.event_id === slug);
if (matching.length === 0) {
  console.error(`No Stripe products found with metadata.event_id = "${slug}".`);
  process.exit(1);
}
console.log(`  ${matching.length} product(s) found`);

const allPrices = await listAll(stripe.prices.list({ limit: 100 }));
const matchingProductIds = new Set(matching.map((p) => p.id));
const pricesForProduct = (productId: string): PriceDefinition[] =>
  allPrices
    .filter((p) => p.active && (typeof p.product === 'string' ? p.product === productId : p.product.id === productId))
    .map((p) => ({
      nickname: p.nickname ?? '',
      unitAmount: p.unit_amount ?? 0,
      currency: p.currency,
      metadata: (p.metadata ?? {}) as Record<string, string>,
    }));

const products: ProductDefinition[] = matching
  .filter((p) => p.active)
  .map((p) => ({
    name: p.name,
    description: p.description,
    metadata: (p.metadata ?? {}) as Record<string, string>,
    prices: pricesForProduct(p.id),
  }));

const totalPrices = products.reduce((s, p) => s + p.prices.length, 0);
console.log(`  ${totalPrices} active price(s) across them`);

if (totalPrices === 0) {
  console.warn(`Warning: no active prices found. The exported file will create products without prices when applied.`);
}

// Silence unused warning — products are derived from matching, but matchingProductIds
// keeps a sane reference if we later want to error on stray prices.
void matchingProductIds;

const definition: EventDefinition = {
  eventSlug: slug,
  products,
};

const outPath = arg('out') ?? join(workerDir, 'scripts', 'stripe-definitions', `${slug}.ts`);
const resolvedOut = outPath.startsWith('/') ? outPath : join(process.cwd(), outPath);
mkdirSync(dirname(resolvedOut), { recursive: true });

// util.inspect produces valid JS object syntax: unquoted keys where possible,
// single-quoted strings with proper escaping, nested objects, etc.
const body = inspect(definition, { depth: null, compact: false, breakLength: 100 });

const tsModule = `// AUTO-GENERATED by \`npm run stripe:export -- --slug=${slug}\`.
// Edit by hand and re-commit; re-export will overwrite this file.

import type { EventDefinition } from './_types';

export const definition: EventDefinition = ${body};
`;

writeFileSync(resolvedOut, tsModule);
console.log(`\nWrote ${resolvedOut}`);
console.log(`Apply to another Stripe account with:`);
console.log(`  npm run stripe:apply -- --file=${outPath}`);
