// Shape of a per-event Stripe definition. One TS module per event, committed
// to the repo. Generated by `npm run stripe:export` from a working test setup,
// then applied to test/live by `npm run stripe:apply` to recreate identical
// products and prices in another environment.

export interface PriceDefinition {
  nickname: string;
  unitAmount: number;
  currency: string;
  metadata: Record<string, string>;
}

export interface ProductDefinition {
  name: string;
  description: string | null;
  metadata: Record<string, string>;
  prices: PriceDefinition[];
}

export interface EventDefinition {
  eventSlug: string;
  products: ProductDefinition[];
}
