// AUTO-GENERATED by `npm run stripe:export -- --slug=bbu-26-2`.
// Edit by hand and re-commit; re-export will overwrite this file.

import type { EventDefinition } from './_types';

export const definition: EventDefinition = {
  eventSlug: 'bbu-26-2',
  products: [
    {
      name: 'BBU 26.2',
      description: null,
      metadata: {
        event_id: 'bbu-26-2'
      },
      prices: [
        {
          nickname: 'Camper van',
          unitAmount: 1500,
          currency: 'gbp',
          metadata: {
            addon_type: 'campervan',
            category_kind: 'addon',
            event_id: 'bbu-26-2'
          }
        },
        {
          nickname: 'Spectator',
          unitAmount: 200,
          currency: 'gbp',
          metadata: {
            category_kind: 'spectator'
          }
        },
        {
          nickname: '12 Pairs',
          unitAmount: 8000,
          currency: 'gbp',
          metadata: {
            max_team_size: '2',
            min_team_size: '2'
          }
        },
        {
          nickname: '12 Solo',
          unitAmount: 7000,
          currency: 'gbp',
          metadata: {}
        },
        {
          nickname: '24 Pairs',
          unitAmount: 10500,
          currency: 'gbp',
          metadata: {
            max_team_size: '2',
            min_team_size: '2'
          }
        },
        {
          nickname: 'Last Man Standing',
          unitAmount: 9500,
          currency: 'gbp',
          metadata: {}
        }
      ]
    }
  ]
};
